import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parents[2]))

from perfbound.calibration.constants import DType
from perfbound.calibration.scripts.fit_constants import (
    extract_all_constants,
    read_msprof_csv,
    write_bandwidth_csv,
)


def _write_rows(path: Path, op_name: str, duration_us: float, n_runs: int = 30) -> None:
    path.write_text(
        "op_name,op_type,duration(us),cycles,task_id,core_id\n"
        + "\n".join(
            f"{op_name},bench,{duration_us:.9f},{duration_us * 1850:.3f},{idx},0"
            for idx in range(n_runs)
        )
        + "\n"
    )


def _cube_duration_for(tflops: float) -> float:
    total_flops = 2 * 128 * 128 * 4096 * 30
    return total_flops / (tflops * 1e6)


def _vector_duration_for(gflops: float) -> float:
    total_ops = 256 * 10000
    return total_ops / (gflops * 1e3)


def _mte_duration_for(gbps: float) -> float:
    total_bytes = 131072 * 2 * 1280
    return total_bytes / (gbps * 1000.0)


def test_read_msprof_csv_skips_comments(tmp_path):
    csv_path = tmp_path / "op_summary.csv"
    csv_path.write_text(
        "# generated by msprof\n"
        "op_name,op_type,duration(us),cycles,task_id,core_id\n"
        "cube,bench,1.25,2312.5,7,3\n"
    )

    rows = read_msprof_csv(csv_path)

    assert len(rows) == 1
    assert rows[0].op_name == "cube"
    assert rows[0].duration_us == 1.25
    assert rows[0].task_id == 7
    assert rows[0].core_id == 3


def test_read_msprof_csv_accepts_current_task_duration_headers(tmp_path):
    csv_path = tmp_path / "op_summary.csv"
    csv_path.write_text(
        "Device_id,Task ID,Op Name,OP Type,Task Duration(us),aic_total_cycles\n"
        "0,11,vector_peak_elemwise,vector_peak_elemwise,20.300,35673\n"
    )

    rows = read_msprof_csv(csv_path)

    assert len(rows) == 1
    assert rows[0].op_name == "vector_peak_elemwise"
    assert rows[0].op_type == "vector_peak_elemwise"
    assert rows[0].duration_us == 20.3
    assert rows[0].cycles == 35673
    assert rows[0].task_id == 11


def test_extract_all_constants_from_synthetic_measured_csvs(tmp_path):
    for dtype, tflops in {"fp16": 280.0, "int8": 560.0, "bf16": 280.0}.items():
        _write_rows(tmp_path / f"cube_peak_{dtype}.csv", "cube", _cube_duration_for(tflops))

    for op in ["add", "mul", "max", "min"]:
        _write_rows(tmp_path / f"vector_peak_elemwise_{op}.csv", f"vector_{op}", _vector_duration_for(640.0))
    _write_rows(tmp_path / "vector_peak_transcendental.csv", "vector", _vector_duration_for(160.0))

    for src, dst, gbps in [
        ("gm", "ub", 180.0),
        ("ub", "gm", 175.0),
        ("gm", "l1", 190.0),
        ("l1", "l0a", 350.0),
    ]:
        _write_rows(tmp_path / f"mte_{src}_to_{dst}.csv", "mte", _mte_duration_for(gbps), n_runs=45)

    intercept_us = 2000.0 / 1850.0
    for k_value in [128, 256, 384, 512, 1024, 2048]:
        _write_rows(
            tmp_path / f"mandatory_handoff_K{k_value}.csv",
            "handoff",
            intercept_us + 0.002 * k_value,
        )

    db = extract_all_constants(tmp_path)

    assert not db.validate_p0_constants()
    assert db.cube.throughput[DType.FP16] == pytest.approx(280.0)
    assert db.cube.throughput[DType.INT8] == pytest.approx(560.0)
    assert db.get_constant("P_vector_add_sustained").source == "cce_microbench"
    assert abs(db.mandatory_handoff_cycles - 2000.0) < 1e-6

    csv_path = tmp_path / "bandwidth_910b3.csv"
    write_bandwidth_csv(db, csv_path)
    assert "gm,ub,-1,-1,sustained,180" in csv_path.read_text()


def test_mte_extraction_keeps_fastest_two_thirds(tmp_path):
    csv_path = tmp_path / "mte_gm_to_ub.csv"
    fast_duration = _mte_duration_for(180.0)
    slow_duration = _mte_duration_for(90.0)
    csv_path.write_text(
        "op_name,op_type,duration(us),cycles,task_id,core_id\n"
        + "\n".join(
            f"mte_gm_to_ub,bench,{duration:.9f},{duration * 1850:.3f},{idx},0"
            for idx, duration in enumerate([fast_duration] * 20 + [slow_duration] * 10)
        )
        + "\n"
    )

    from perfbound.calibration.scripts.fit_constants import extract_mte_bandwidth

    constant = extract_mte_bandwidth(csv_path, "gm", "ub")

    assert constant.value == pytest.approx(180.0)
    assert constant.n_runs == 20
